# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tech Telegrams
subtitle: Latest Technology News
email: techtelegrams@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Latest Technology News about Gadgets, Internet and Cloud.
  #logo : "/assets/images/techtelegrams_logo.png"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techtelegrams.com"

minimal_mistakes_skin: default
search: true


# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.md
  - build.sh

author:
  name   : "Tech Telegrams"
  #avatar : "/assets/images/techtelegrams_logo.png"
  bio    : "Latest Technology news"
  links:
      #- label: "Website"
      #icon: "fas fa-fw fa-link"
      #url: "https://"
      #- label: ""
      #icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/TechTelegrams"
      #- label: ""
      #icon: "fab fa-fw fa-google"
      #url: "https://news.google.com/publications/CAAqBwgKMJe5mwsw28OzAw?hl=en-IN&gl=IN&ceid=IN:en"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TechTelegrams"
    - label: "Google"
      icon: "fab fa-fw fa-google"
      url: "https://news.google.com/publications/CAAqBwgKMJe5mwsw28OzAw?hl=en-IN&gl=IN&ceid=IN:en"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

analytics:
  provider: google-gtag
  google:
    tracking_id: UA-170112886-1

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
